add enterprise vpn
opentelekomcloud-infra/stackmon-config pull request #179
Opened 2024-12-13 16:24 UTC by lhajba

2024-12-18 08:52 UTC, PotPlayer553 commented
永远能连上的VPN

    自主研发协议， 断网期也能用

    稳定运营6年从未中断过

    永不限速，网有多快，快连就多快

    累计超过2000万用户下载。

安全VPN推荐（最高优惠链接:)
https://expvpn.net
https://vpndapps.com
https://letsvpnt.com
https://letskuailian.com

2025-02-26 12:51 UTC, vladimirhasko requested changes

2025-02-26 12:51 UTC, vladimirhasko commented on mp-prod/conf.d/health_metrics.yaml
> +      - vpn.api_down
evpn

2025-02-26 12:51 UTC, vladimirhasko commented on mp-prod/conf.d/health_metrics.yaml
> +      - vpn.api_slow
evpn

2025-02-26 12:51 UTC, vladimirhasko commented on mp-prod/conf.d/health_metrics.yaml
> +      - vpn.api_success_rate_low
evpn

2025-02-26 14:55 UTC, merged